# Copyright (c) 2023, NVIDIA CORPORATION.  All rights reserved

#local machine
root: "<root>/_exp"
save_evolution: False
ckpt_root: "ckpts"
samples_root: "samples"
overwrite: True
num_steps: 50
t_start: 0
t_end: 1000
stride: ddpm_uniform
smoke_test: 4
logfreq: 200
save_ori: False
save_deg: False
seed: 1
res_file_name: results.csv
name: ???
